### ISSUE TITLE
网页内容更新

### ISSUE THREAD

**Issue by Cubik65536** [NewNanCity/NewNanCity-OfficialWebsite#6]
网页部分老旧内容需要更新：
- 更新主页背景图片
- 更新`基础介绍.html`内关于主城的内容（已更换新主城）
- Wiki更新
  - `/trigger menu` 命令的使用

还有其他需要补充的吗

**Comment by Cubik65536** [comment]
添加：
- 关于资源下届的命令

**Comment by Gk0Wk** [comment]
好耶

**Comment by Cubik65536** [comment]
> 好耶

主城内容没改啊... 命令也没加啊...

**Comment by Cubik65536** [comment]
我抽时间做吧

**Comment by Cubik65536** [comment]
TODO 2021/06/25
- 更新基础介绍.html内关于主城的内容（已更换新主城）
- Wiki更新
  - /trigger menu 命令的使用
  - 关于资源下届的命令

**Comment by Cubik65536** [comment]
用Notion了直接close了吧
